#!/bin/bash

# First, accept all traffic coming from the VPN:
sudo iptables -A INPUT -s 192.168.30.1/24 -m state --state NEW -j ACCEPT
sudo iptables -A OUTPUT -s 192.168.30.1/24 -m state --state NEW -j ACCEPT
sudo iptables -A FORWARD -s 192.168.30.1/24 -m state --state NEW -j ACCEPT

#Also accept all traffice from established connections:

sudo iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
#Finally, forward all traffic from the tap device to the internet interface. If you use a static IP address on the server, use this command:

sudo iptables -t nat -A POSTROUTING -s 192.168.30.1/24 -j SNAT --to-source 195.201.101.101
#If your public IP address is not static, use this command:

sudo iptables -t nat -A POSTROUTING -s 192.168.30.1/24 -o eth0 -j MASQUERADE

# forwarding traffice to squid from 192.168.30.1/24
iptables -t nat -A PREROUTING -s 192.168.30.1/24 -p tcp -m multiport --dport 80 -j DNAT --to-destination 127.0.0.1:8080
